run cypress in same step as vite

diff --git a/.github/workflows/ui.yml b/.github/workflows/ui.yml
--- a/.github/workflows/ui.yml
+++ b/.github/workflows/ui.yml
@@ -67,16 +67,17 @@ jobs:
       - name: Create react app and serve
         run: |
           npx vite --host &
+          npx cypress run
 
       # - name: IP
       #   run: |
       #     hostname -i
-      - name: Add hosts to /etc/hosts
-        run: |
-            HOSTNAME=$(hostname -i)
-            sudo echo "${HOSTNAME} localhost" | sudo tee -a /etc/hosts
-            sudo cat /etc/hosts
-            echo "HOSTNAME=${HOSTNAME}" >> $GITHUB_ENV
+      # - name: Add hosts to /etc/hosts
+      #   run: |
+      #       HOSTNAME=$(hostname -i)
+      #       sudo echo "${HOSTNAME} localhost" | sudo tee -a /etc/hosts
+      #       sudo cat /etc/hosts
+      #       echo "HOSTNAME=${HOSTNAME}" >> $GITHUB_ENV
 # npm create vite@latest my-app -- --template react-ts
 # cd my-app
 # npm i
@@ -92,27 +93,27 @@ jobs:
 # })
 # EOF
 
-      - name: Run UI tests
-        uses: cypress-io/github-action@v5
-        id: cypress
-        continue-on-error: true
-        with:
-          record: true
-          install: false
-          wait-on: 'http://localhost:8000'
-          config-file: cypress.config.ts
-          command-prefix: "--"
-          # config: baseUrl=http://${{ env.HOSTNAME }}:8000
-        env:
-          ELECTRON_ENABLE_LOGGING: 1
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
+      # - name: Run UI tests
+      #   uses: cypress-io/github-action@v5
+      #   id: cypress
+      #   continue-on-error: true
+      #   with:
+      #     record: true
+      #     install: false
+      #     wait-on: 'http://localhost:8000'
+      #     config-file: cypress.config.ts
+      #     command-prefix: "--"
+      #     # config: baseUrl=http://${{ env.HOSTNAME }}:8000
+      #   env:
+      #     ELECTRON_ENABLE_LOGGING: 1
+      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+      #     CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
       
-      - name: Print Cypress Cloud URL
-        run: |
-          echo Cypress finished with: ${{ steps.cypress.outcome }}
-          echo See results at ${{ steps.cypress.outputs.resultsUrl }}
-          exit ${{ fromJSON('["0", "1"]')[steps.cypress.outcome == 'failure'] }}
+      # - name: Print Cypress Cloud URL
+      #   run: |
+      #     echo Cypress finished with: ${{ steps.cypress.outcome }}
+      #     echo See results at ${{ steps.cypress.outputs.resultsUrl }}
+      #     exit ${{ fromJSON('["0", "1"]')[steps.cypress.outcome == 'failure'] }}
 
       - name: Build app [dev]
         run: pnpm run build:ui && echo "AWS_S3_BUCKET=${AWS_S3_BUCKET}" >> $GITHUB_ENV && echo "CF_DISTRO_ID=${CF_DISTRO_ID}" >> $GITHUB_ENV
